export const CERTIFICATES = [

  { title: "Full Stack WebDev", category: "adv" },
  { title: "Responsive WebDesign", category: "adv" },
  { title: "HTML5 Champion", category: "adv" },
  { title: "Advanced SQL Analytics", category: "adv" },
  { title: "DSGVO Certified", category: "adv" },
  { title: "MySQl for Data Analysis", category: "adv" },

  { title: "Basic HTML", category: "web" },
  { title: "CakePHP", category: "web" },
  { title: "Dynamic Web Forms with validation", category: "web" },
  { title: "GitHub Grundlagen", category: "web" },
  { title: "HTML5", category: "web" },
  { title: "HTML Bootcamp", category: "web" },
  { title: "Web Development Crash Course", category: "web" },
  { title: "HTML5 and CSS3", category: "web" },
  { title: "InfiniteScroll AJAX", category: "web" },
  { title: "Landing Page Hacks", category: "web" },
  { title: "HTML5 and CSS3 by Coding", category: "web" },
  { title: "Learn HTML5", category: "web" },
  { title: "Make Ecommerce Website Front-End", category: "web" },
  { title: "PHP&MySQL", category: "web" },
  { title: "PSD Frontend", category: "web" },
  { title: "Telegram Bot with Python", category: "web" },
  { title: "XHTML-01", category: "web" },
  { title: "XHTML-02", category: "web" },
  { title: "XHTML-03", category: "web" },
  { title: "XHTML-04", category: "web" },
  { title: "XHTML-05", category: "web" },
  { title: "XHTML-06", category: "web" },
  { title: "XHTML-07", category: "web" },
  { title: "Yii PHP Framework", category: "web" },

  { title: "Amazon FBA", category: "other" },
  { title: "eBay Dropshipping", category: "other" },
  { title: "Exel 2010 Productivity", category: "other" },
  { title: "Godot Game Engine", category: "other" },
  { title: "Google Sheets", category: "other" },
  { title: "Google Docs", category: "other" },
  { title: "Grundlagen Vermögensverwaltung", category: "other" },
  { title: "Landschaftsfotografie", category: "other" },
  { title: "Microsoft Exel Pivot", category: "other" },
  { title: "Startup & Business", category: "other" },
  { title: "Visual Studio Code Hacks", category: "other" },

  { title: "Robocup 2014", category: "robotic" },
  { title: "Robocup 2015", category: "robotic" },
  { title: "Robocup 2016", category: "robotic" },
  { title: "Robotik", category: "robotic" },
  { title: "Mechatronik Seminar", category: "robotic" },

  { title: "146. Jugend Presse Kongress", category: "newspaper" },
  { title: "150. Jugend Presse Kongress", category: "newspaper" },
  { title: "Multimedia Workshop", category: "newspaper" },

];